language:node_js
node_js:
 - "7"

sudo : required
services:
  - docker
before_install:
  - docker build -t jaydeepgami56/docker-react -f Dockerfile.dev .

scripts:
  - docker run   jaydeepgami56/docker-react npm run test 
